name: web_color_picker
description: This package allows you use the native web browser color picker in your Flutter Web app. 
version: 1.0.3
repository: https://github.com/victoreronmosele/flutter_web_color_picker
issue_tracker: https://github.com/victoreronmosele/flutter_web_color_picker/issues

topics:
  - html
  - color-picker
  - widget
  - color
  - web

platforms:
  - web

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.13.6"

dependencies:
  flutter:
    sdk: flutter
  mocktail: ^1.0.1
  universal_html: ^2.2.4
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: 

flutter:
  

screenshots:
  - description: "This screenshot shows a custom color picker selector displayed with the web_color_picker package."
    path: screenshots/screenshot.png
  - description: "This gif demonstrates the color picker events using a custom selector and the default selector"
    path: screenshots/web_color_picker_events.gif
  - description: "This gif shows a custom color picker selector displayed with the web_color_picker package."
    path: screenshots/web_color_picker.gif
  - description: "This gif shows the browser's default color picker displayed with the web_color_picker package."
    path: screenshots/web_color_picker.gif

